
# Use the Alpine Linux (a lightweight Linux distribution often used for minimal Docker images) as the base image
# Image is pulled from Docker Hub Registry like we pull jar files from Maven Central
FROM alpine

# Set the command to execute when a container is started
# ls command, which lists the files and directories in the container's working directory.
CMD ["ls"]