# Assume hi
FROM openjdk:11-jdk
WORKDIR /app
ADD . /app

# runs the Maven wrapper (mvnw) to build a Java application using the "package" goal.
RUN ./mvnw package

# we don't need whole jdk or maven or source code to run the jar
CMD ["java", "-jar", "layerdemo-0.0.1-SNAPSHOT.jar"]